### ISSUE TITLE
PWA not working 

### ISSUE THREAD

**Issue by gregpetru** [gregpetru/ESPresso32#7]
<img width="1039" alt="Screenshot 2024-11-20 alle 14 34 36" src="https://github.com/user-attachments/assets/d2e2bb0d-5d07-4edc-9c5b-85113245bfbf">

@ali-benny Qualcosa non funziona

**Comment by ali-benny** [comment]
Ma wtffffffffff

**Comment by ali-benny** [comment]
okay okay tolgo public
